# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fc5bf42449b74b09956f7ec5817a77f5a9ea07354769adf98a94ff327fbff6a8e9c2623f289a9ad06ef0e8f18764c544625d4e81556bd4dcb13a9bf89540433

test:
  secret_key_base: ee1b4af3ccbc1b2e62c9538c11a7e3c358391eb31be3d82dafd6402e39f442ab5426abcc05c92ece1981e906762054ff57545a846d3d1e99a6e318df87366745

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
